Fixes #22837 - postpone validation checks in Rails environment
Otherwise, the actions performed during the validity check could lead to
issues like this:

    RuntimeError: The Dynflow world was not initialized yet. If your plugin
    uses it, make sure to call Rails.application.dynflow.require! in some
    initializer